import type { PostcardMemory } from '@/types/memory'

export const POSTCARDS: PostcardMemory[] = [
  {
    id: 'postcard-001',
    category: 'postcard',
    title: 'Tokyo',
    location: {
      scene: 'main-hall',
      description: 'On the lost & found counter, face-down',
      visualHint: { x: 65, y: 50 },
    },
    animation: { type: 'flip', duration: 600, reversible: true },
    audio: { sfx: 'postcard-flip' },
    unlockCondition: { type: 'free' },
    notebookSection: 2,
    notebookOrder: 1,
    destination: 'Tokyo, Japan',
    frontImage: '/images/memories/postcards/tokyo.jpg',
    backText: 'I keep picturing us getting lost in these streets together, no map, no plan.',
    stampRegion: 'Japan',
    postmarkDate: 'Soon',
  },
  {
    id: 'postcard-002',
    category: 'postcard',
    title: 'Paris',
    location: {
      scene: 'platform-cafe',
      description: 'Wedged between books on the café shelf',
      visualHint: { x: 80, y: 35 },
    },
    animation: { type: 'flip', duration: 600, reversible: true },
    audio: { sfx: 'postcard-flip' },
    unlockCondition: { type: 'free' },
    notebookSection: 2,
    notebookOrder: 2,
    destination: 'Paris, France',
    frontImage: '/images/memories/postcards/paris.jpg',
    backText: 'Even here, I\'d still rather be looking at you than at the tower.',
    stampRegion: 'France',
    postmarkDate: 'Soon',
  },
  {
    id: 'postcard-003',
    category: 'postcard',
    title: 'Swiss',
    location: {
      scene: 'waiting-room',
      description: 'Inside the vinyl record sleeve on the shelf',
      visualHint: { x: 25, y: 40 },
    },
    animation: { type: 'flip', duration: 600, reversible: true },
    audio: { sfx: 'postcard-flip' },
    unlockCondition: { type: 'free' },
    notebookSection: 2,
    notebookOrder: 3,
    destination: 'The Alps, Switzerland',
    frontImage: '/images/memories/postcards/swiss.jpg',
    backText: 'The quiet up here would mean more with you next to me.',
    stampRegion: 'Switzerland',
    postmarkDate: 'Soon',
  },
  {
    // Not a memory of somewhere we've been — the only one of the four
    // that looks forward instead of back. Placed late in the ride, once
    // the window's own dawn-rise has had time to soften the carriage.
    id: 'postcard-004',
    category: 'postcard',
    title: 'Maldives',
    location: {
      scene: 'final-carriage',
      description: 'Resting on the windowsill, like it\'s been waiting for the light to come up',
      visualHint: { x: 74, y: 30 },
    },
    animation: { type: 'flip', duration: 600, reversible: true },
    audio: { sfx: 'postcard-flip' },
    unlockCondition: { type: 'act-reached', actId: 'act-journey' },
    notebookSection: 2,
    notebookOrder: 4,
    destination: 'Ayada, Maldives',
    frontImage: '/images/memories/postcards/maldives.jpg',
    backText: 'Somewhere we haven\'t been yet — but I can already picture us there.',
    stampRegion: 'Maldives',
    postmarkDate: 'SOMEDAY',
  },
]
