// ─────────────────────────────────────────────────────────────────────────────
// Hidden Letters
// Never placed in a scene, never clicked to find — these live only in the
// notebook's "Hidden" section. Five unlock quietly each time one of the 20
// real collectibles is found, so all 100 are already there by the time
// everything else has been. The final letter already says it:
// "There were never one hundred reasons. There were only one hundred moments."
// This is that hundred, made real.
// ─────────────────────────────────────────────────────────────────────────────

import type { HiddenLetterMemory } from '@/types/memory'

const HIDDEN_LETTER_LINES: string[] = [
  `I didn't fall for you all at once — it happened slowly, in a thousand small moments. Your laugh, your kindness, the way you show up. All of it added up to this. ❤️`,
  `Every day gives me another reason to admire you. Sometimes it's something you say, sometimes it's just the way you are.`,
  `You walked into my life so quietly that I didn't notice everything had changed until every happy thought started leading back to you.`,
  `There are countless beautiful things in this world, but my eyes always end up looking for you anyway. 😍`,
  `Somehow you turn the simplest conversations into memories I don't want to lose.`,
  `If I met you again for the very first time, I'd still hope our conversation ran too long. I'd still fall for you, exactly the same way.`,
  `My favorite thing about loving you isn't the excitement — it's the quiet comfort of knowing my heart is exactly where it's supposed to be.`,
  `The way you say my name when you're a little annoyed with me is softer than you think.`,
  `I hope life gives you a thousand reasons to smile. Selfishly, I hope I get to be a few of them. 🥰`,
  `You make me appreciate the smallest moments — a message, a shared laugh, a few minutes together.`,
  `You fall asleep mid-sentence sometimes, and I just keep talking anyway so you can read it when you wake up.`,
  `Seeing you happy has become one of my favorite feelings, even when I'm not the reason for it.`,
  `If my heart could write letters on its own, every page would somehow end with you in it.`,
  `Even your bad days end with you asking about mine. That tells me everything about how you love.`,
  `You don't realize how often you become the best part of my day without even trying.`,
  `If I had one small wish, it wouldn't be for anything grand — just more ordinary time with you. ❤️`,
  `I love that I never have to search for reasons to love you. They just show up. 🥰`,
  `Being around you reminds me that comfort isn't a place. Sometimes it's just a person.`,
  `You have a way of making me feel understood without needing the perfect words.`,
  `If someone asked me for my favorite memory, I couldn't pick just one — every laugh, every late conversation, they all blur into one long good thing.`,
  `I never want to let an argument end without making sure we're okay first.`,
  `Loving you never felt like chasing something impossible. It felt like finally arriving somewhere.`,
  `The way you say "I'm proud of you" like it costs nothing, when it means everything to me.`,
  `I hope I never stop noticing the little things about you — the habits, the small expressions nobody else catches.`,
  `I hope that in every lifetime, somehow, our paths still find each other.`,
  `You never asked to become my favorite person. You just are. 😍`,
  `You're the first person I want to tell good news to, and the last smile I want to see before the day ends.`,
  `You still get excited to tell me the small things, and I love hearing every one of them.`,
  `I never knew you could miss someone while they were right in front of you, until I met you.`,
  `Every new thing I learn about you feels like one more reason I'm glad I found you.`,
  `You've never made me feel like I was too much, and I don't take that for granted.`,
  `Sometimes you look at me like I said something your heart already knew.`,
  `I hope years from now, we're still finding reasons to smile at each other for no reason at all.`,
  `You laugh at the same jokes every time, like they're new. 🥰`,
  `You became part of my everyday without ever asking to be, and now nothing feels complete without you in it.`,
  `Sometimes I catch myself smiling at my phone for no reason, and it's always because of you. 😍`,
  `You don't try to be charming. You just are, and that might be the most dangerous thing about you. 😘`,
  `I like how you make plans with "us" already built into them.`,
  `I like who I am around you — the version that laughs more and worries less.`,
  `Every conversation with you ends the same way: I'm already looking forward to the next one.`,
  `I hope we're still teasing each other about the same old things years from now.`,
  `You make me feel like the most interesting person in the room, and I don't know how you do that. 🥰`,
  `You'll never have to earn my affection. You already have it, just by being you.`,
  `I didn't know someone could feel like home without being a place at all.`,
  `You make me feel excited and calm at the exact same time. I didn't know that was possible.`,
  `You have a habit of showing up in my thoughts when I'm supposed to be focused on something else. 😘`,
  `I'd happily lose every argument if the prize was one of your smiles.`,
  `If hugs could be sent through thought alone, you'd wonder why you keep feeling one out of nowhere. 🥰`,
  `I don't think there's a limit to how many times I can hear your voice and still want to hear it a little longer.`,
  `You've become the person I tell everything to — the big wins and the tiny random thoughts alike.`,
  `I don't need perfect timing with you. I just need more time with you.`,
  `You've never made me feel unheard, even when we disagreed.`,
  `The way you say "our place," "our song," "our thing" without a second thought — it's the small stuff that gets me. 🥰`,
  `Every little thing you remember about me feels like a small love letter you didn't know you were writing.`,
  `You've spoiled my heart. Now it expects something good every time your name shows up.`,
  `If someone could see my thoughts, they'd assume you'd taken over the whole place.`,
  `You make plans for a future that doesn't exist yet, like it's obvious we'll get there. I think we will.`,
  `I hope you never stop letting me see the parts of you nobody else notices. Those are my favorites.`,
  `I don't think I'll ever get used to being excited to see you.`,
  `You've become my favorite reason to look forward to tomorrow.`,
  `I like imagining all the tiny memories we haven't made yet. They already feel important.`,
  `If I had to describe comfort, I'd probably end up describing you without meaning to.`,
  `You've been stealing my attention all day again, and I'm not even mad about it. 😘`,
  `Every time you smile, I forget whatever I was about to say. 😍`,
  `If staring into your eyes counted as exercise, I'd be in great shape by now. 😍`,
  `Every little thing about you has become a favorite of mine — not because it's perfect, but because it's yours.`,
  `No matter how many conversations we've had, I still get excited for the next one, every time.`,
  `You have a way of making life feel softer. Even busy days slow down a little when you're in them.`,
  `I never believed a thought could become a favorite until you quietly claimed that spot.`,
  `I won't let you carry something heavy without at least offering to help.`,
  `When I say I'm not going anywhere, it's because I mean it, not because it's easy to say.`,
  `You make me want to be better, without ever once asking me to be.`,
  `My eyes have gotten a little spoiled — after seeing you, they keep looking for you everywhere. 🥰`,
  `The way you say "us" like it's the most natural word you know.`,
  `You still get a little nervous around me sometimes, in the best way. 🥰`,
  `You've made it impossible for a "good day" to exist without you somehow being part of it.`,
  `The way you say "always" doesn't sound like a cliché when it's you saying it.`,
  `Every plan I make for the future somehow already has you in it. It happens without me even deciding.`,
  `Somewhere between the conversations and the laughing, you quietly became my favorite person.`,
  `I like imagining all the small memories we're going to make by accident.`,
  `You're proof that someone doesn't have to be loud to completely change another person's life.`,
  `If affection left footprints, mine would always lead back to you.`,
  `I don't chase perfect moments. I just look for moments with you in them, and they turn out fine anyway.`,
  `I love how your whole face changes when you're talking about something you love. 😍`,
  `Every little thing you share with me feels like another page in my favorite story.`,
  `Every time you call me something sweet, my brain forgets how words work for a second. 🥰`,
  `You make room for me in your day without ever making it feel like a favor.`,
  `I have a real problem — every time I try to stop smiling because of you, you give me another reason to. 😘`,
  `I don't want our best memories to be the extraordinary ones. I want them to be the ordinary Tuesdays, the sleepy conversations, the walks with nowhere to be.`,
  `I hope you never get tired of hearing how much you mean to me.`,
  `Getting to know you little by little — not all at once, but through small conversations and quiet moments — was one of the luckiest things that ever happened to me.`,
  `Every new thing I learn about you makes me admire you a little more. My heart keeps finding new reasons to stay right here.`,
  `If I could give you one thing that cost nothing, I'd let you see yourself the way I see you, just for a few minutes.`,
  `I can't really picture what my life would look like if our paths had never crossed. You've become part of the routine of it.`,
  `When you tell me about your day, I listen a little more carefully than I let on. The small pieces of it matter to me too.`,
  `The way you make hard days easier just by being in the room is something I still haven't figured out. It's just you.`,
  `I don't love some polished version of you. I love the real one — the one who gets sleepy, laughs too hard, and overthinks sometimes.`,
  `I hope today reminds you how appreciated you are, and how quietly you've become my favorite part of the world.`,
  `Even on the days we're far apart, I find myself narrating little pieces of my day to you in my head anyway.`,
  `I catch myself drafting the message before I've even decided to send it — a strange sky, a funny stranger's dog, something small I want you to see too. You've become the person I explain my world to, even when you're not there to hear it. 💞`,
]

const INK_VARIATIONS = ['light', 'medium', 'heavy'] as const

export const HIDDEN_LETTERS: HiddenLetterMemory[] = HIDDEN_LETTER_LINES.map((body, i) => ({
  id: `hidden-letter-${String(i + 1).padStart(3, '0')}`,
  category: 'hidden-letter',
  title: `Moment ${i + 1}`,
  location: {
    scene: 'main-hall',
    description: 'Not placed anywhere — this one only ever lives in the notebook.',
  },
  animation: { type: 'unfold', duration: 500, reversible: true },
  audio: { sfx: 'paper-unfold' },
  unlockCondition: { type: 'free' },
  notebookSection: 11,
  notebookOrder: i + 1,
  date: `Moment ${i + 1} of 100`,
  body,
  signature: '— R',
  inkVariation: INK_VARIATIONS[i % 3] ?? 'medium',
  paperRotation: ((i % 7) - 3) * 0.6,
}))
