// ─────────────────────────────────────────────────────────────────────────────
// Hidden Letters
// Never placed in a scene, never clicked to find — these live only in the
// notebook's "Hidden" section. Five unlock quietly each time one of the 20
// real collectibles is found, so all 100 are already there by the time
// everything else has been. The final letter already says it:
// "There were never one hundred reasons. There were only one hundred moments."
// This is that hundred, made real.
// ─────────────────────────────────────────────────────────────────────────────

import type { HiddenLetterMemory } from '@/types/memory'

const HIDDEN_LETTER_LINES: string[] = [
  `I didnt fall for you all at once, It happened slowly, in thousands of little moments. Your laugh, your beautiful smile, your kindness, your humour, your care, your sweet side, your bitter side, your presence. Everything has contributed to my feelings for you.❤️`,
  `Every day gives me another reason to admire you. Sometimes it's something you say, sometimes it's the way you care, and sometimes it's simply because you're being yourself.`,
  `You walked into my life so quietly that I didn't realize everything had changed until one day I noticed that every happy thought somehow led back to you.`,
  `There are countless beautiful things in this world, but somehow my eyes always end up looking for you. Because, You will always be the most beautiful person in my eyes. 😍`,
  `Somehow you turn the simplest conversations into memories that I never want to lose.`,
  `If I had the chance to meet you again for the very first time, I'd still hope our conversations lasted longer than they should. And I'd still end up falling for you, knowing exactly how worth it you are.`,
  `My favorite thing about loving you isn't the butterflies or the excitement. It's the quiet comfort of knowing that whenever I think about you, my heart feels like it's exactly where it's supposed to be.`,
  `The way you say my name when you're annoyed with me is softer than you think.`,
  `I hope life gives you a thousand reasons to smile, but selfishly, I hope, I get to be at least a few reasons of them. 🥰`,
  `You make me appreciate the smallest moments.Even just A message from you, or a laugh we share,or even a few minutes together.`,
  `The way you fall asleep mid conversation and I just tend to finish the conversation anyways even tho I know youre asleep so you could just read it when you wake up.`,
  `Seeing you happy has become one of my favorite feelings, even when I'm not the reason behind it.`,
  `If my heart could write letters on its own, every page would somehow end with your name. Not because it has nothing else to say, but because every beautiful thought eventually finds its way back to you.`,
  `How your bad days somehow still end with you asking about mine, showing you do care always.`,
  `I don't think you realize how often you become the best part of my day without even trying.`,
  `If I had one tiny wish, it wouldn't be for anything grand. I'd just ask for more moments with you, more conversations that last too long, more reasons to laugh together, and more memories that we'll accidentally create without even planning them. ❤️`,
  `I love that I don't have to search for reasons to love you. They appear on their own every single day. 🥰`,
  `Just being around you reminds me that comfort isn't always a place. Sometimes, it's simply one person who makes everything else feel a little less complicated.`,
  `You have this way of making me feel understood without needing perfect words.`,
  `If someone ever asked me what my favorite memory is, I don't think I could choose just one. Every time we laugh together, every conversation that keeps us awake a little longer, and every quiet moment we share. they all become little pieces of a life I never want to forget.`,
  `I will never let an argument end without checking that we're still okay at the end.`,
  `Loving you has never felt like chasing something impossible. It feels like slowly discovering a place where my heart belongs naturally`,
  `The way you say "I'm proud of you" like it costs you nothing, when it means everything to me.`,
  `I hope there never comes a day when I stop noticing the little things about you. The tiny habits, the expressions you don't realize you make, the small moments that nobody else pays attention to. they've become some of my favorite things in the world.`,
  `I hope that somewhere in every single lifetime, our paths always find each other`,
  `You didn't ask to become my favorite person, yet here you are. 😍`,
  `You are the first thought I want to share good news with, the first smile I want to see after a long day, and the person who somehow makes tomorrow feel exciting.`,
  `You still get excited to tell me things, even the small ones, and I love to hear every single one of them.`,
  `I never knew that missing someone could happen even while you're still talking to them in the moment, until I met you.`,
  `Every time I learn something new about you, I don't feel like I'm collecting facts. I feel like I'm discovering another beautiful reason why meeting you became one of the luckiest moments of my life.`,
  `You've never made me feel like I am too much, and I appreciate it a lot.`,
  `The way sometimes you look at me like I said something your heart didn't already know.`,
  `I hope years from now, when life has changed in ways we can't imagine yet, we still find ourselves smiling at each other for no reason at all.`,
  `You laugh at my same jokes every time like they're new to you always. 🥰`,
  `I love how you've become part of my everyday without ever asking to be. Now every little thing feels like it would be better if you were there to experience it with me.`,
  `Sometimes I wonder if you know that you're the reason I smile at my phone like an idiot. 😍`,
  `You don't even have to try to be adorable, You are naturally adorable. That's honestly the most dangerous thing about you. 😘`,
  `The way you make plans with "us" already built into them.`,
  `I love the version of myself that exists around you. The one that laughs more, worries less, and somehow believes everything will be okay.`,
  `Every conversation with you ends the same way. I already can't wait for the next one.`,
  `I secretly hope that years from now we'll still be teasing each other over the same silly things and laughing just as hard as we do now.`,
  `How you make me feel like the most interesting one in the room is so cute of you. 🥰`,
  `I hope you always know this: you'll never have to earn my affection. You already have it, simply by being you.`,
  `I didn't realize someone could become my favorite place without being a place at all.`,
  `You somehow make me feel both excited and peaceful at the exact same time. I didn't even know that was possible until I found you.`,
  `You have this habit of showing up in my thoughts when I'm supposed to be concentrating. Honestly, you're the cutest distraction I will ever allow. 😘`,
  `I'll happily lose every argument if the prize at the end was getting one of your smiles.`,
  `I wish hugs could be delivered through thoughts, you'd probably be wondering why you're being hugged every minute. 🥰`,
  `I don't think there's a limit to how many times I can hear your voice and still wish you'd talk just a little longer.`,
  `I love how naturally you've become the person I tell everything to, from the biggest victories to the tiniest random thoughts.`,
  `I don't need perfect timing with you. I just need more time with you.`,
  `You've never let me feel unheard, even when we disagreed.`,
  `The way you say "our place," "our song," "our thing," without a second thought, It's so cute and adorable. 🥰`,
  `Every little thing you remember about me feels like a tiny love letter you didn't even realize you were writing for me.`,
  `You make my heart feel spoiled. Now it expects excitement every time your name appears on my screen.`,
  `If someone could see inside my thoughts, they'd probably assume you've own the place.`,
  `How you make plans for a version of us that doesn't exist yet, like it's obvious we'll get there, We will be there.`,
  `I hope you never stop letting me see the little parts of you that nobody else notices. Those are my favorite.`,
  `I don't think I'll ever outgrow getting excited to see you or talk to you.`,
  `You've become my favorite reason to look forward to tomorrow.`,
  `I like imagining all the tiny memories we haven't made yet. Somehow they already feel precious.`,
  `If I had to describe what comfort feels like, I'd probably end up describing you without even realizing it.`,
  `I think you owe me something Milady... You've been stealing my attention all day whenever we talk. 😘`,
  `Every time you smile, you accidentally make it impossible for me to remember what I was about to say. 😍`,
  `I wish staring into your eyes was an exercise, I'd be the healthiest person alive. 😍`,
  `Every little thing about you has become a favorite of mine. Not because it's perfect, but because it's yours.`,
  `I love that no matter how many conversations we have, I still get excited for the next one like it's our first.`,
  `You have this wonderful habit of making life feel softer. Even busy days seem to slow down whenever you're part of them.`,
  `I never believed someone could become my favorite thought until you quietly claimed that spot without even trying.`,
  `I Promise, I will never let you carry something heavy without offering to carry it too.`,
  `When I say "I'm not going anywhere" is out of my heart, because it knows. I'll not leave you alone.`,
  `It's so amazing, How you make me want to be a better version of myself, without ever asking me to be.`,
  `I think my eyes have become a little spoiled. After seeing you, they keep looking for you everywhere. 🥰`,
  `The way you say "us" like it's the most natural word you know, and I love it.`,
  `How you still get nervous around me, in the good way. 🥰`,
  `I hope you know you've made it impossible for "good days" to exist without you somehow being part of them.`,
  `The way you say "always" and somehow make it sound like a promise,It's not a cliché.`,
  `How every plan I make for the future has you in it, without me even deciding that on purpose, it just comes naturally like "us" yes Me and You.`,
  `Somewhere between our conversations and our laughter, you quietly became my favorite person.`,
  `I like imagining all the tiny memories we're going to accidentally create together.`,
  `You're proof that someone doesn't have to be loud to completely change another person's life.`,
  `If affection could leave footprints, mine would always lead to you every single time.`,
  `I don't chase perfect moments. I just look for moments that include you and it automatically becomes perfect.`,
  `I Love How your whole face changes when you talk about something you love. 😍`,
  `Every little thing you share with me feels like adding another page in my favorite story.`,
  `Every time you call me cute, my brain forgets how words work for a few seconds. 🥰`,
  `How you make room in your day for me without ever making it feel like a favor to me.`,
  `I have a serious problem. Every time I try to stop smiling because of you... you give me another reason to smile. 😘`,
  `I don't want our happiest memories to be the extraordinary ones. I want them to be the everyday ones the random Tuesday afternoons, the sleepy conversations, the shared desserts, the walks with nowhere to be. Those are the moments that quietly become forever.`,
  `I hope you never get tired of me telling you how much you mean to me.`,
  `I think one of the luckiest things that ever happened to me was getting to know you little by little. Not all at once, not through grand moments, but through tiny conversations, random laughs, and the countless little pieces of yourself that you've trusted me enough to see.`,
  `Every new thing I learn about you somehow makes me admire you even more. It's like my heart keeps discovering new reasons to stay exactly where it already wanted to be.`,
  `If I could give you one gift that didn't cost anything, I'd let you see yourself through my eyes for just a few minutes. You'd finally understand why I smile whenever your name appears, why I notice the tiniest things about you, and why spending even a little bit of time with you feels like the best part of my day.`,
  `Sometimes I wonder what my life would look like if our paths had never crossed. I honestly can't picture it anymore. You've become such a natural part of my thoughts, my routines, my happiest moments, that imagining a version of life without you feels strangely incomplete. I'm really grateful that somehow, out of all the people in this world, I found you.`,
  `Every time you tell me about your day, I listen a little more carefullybecause, I like knowing what made you laugh, what frustrated you, what made you smile, and what made you stop and think. Those little pieces of your day somehow become little pieces of mine too.`,
  `How you make the hard days easier just by being in the room needs to be studied, It's naturally unique.`,
  `You don't have to have the perfect words, the perfect mood, or the perfect day. I don't love some polished version of you. I love the real one. The one who gets sleepy, laughs too hard, overthinks sometimes, gets excited about random things, and simply exists in the wonderfully unique way that only you can.`,
  `I hope today reminds you how deeply you're appreciated, how genuinely you're admired, and how quietly you've become my favorite part of the world.`,
  `The distance between us has started to feel like a language of its own, one I'm slowly learning to read. Every time zone we don't share becomes a small riddle I solve just to imagine what you're doing in that exact minute maybe brushing your hair? or laughing at something on your phone? or maybe, if I'm lucky, thinking of me too.`,
  `Do you know that I've started narrating my day to you in my head, even when we're not talking? I'll see a dog that is walking funnyly, or a sky doing where clouds are making amazing shapes, and my brain immediately drafts the text I'll send you about it. You've become the person I explain my world to, even in your absence, I chose You, I will always chose You. ILoveYou very much my Baby. 💞`,
]

const INK_VARIATIONS = ['light', 'medium', 'heavy'] as const

export const HIDDEN_LETTERS: HiddenLetterMemory[] = HIDDEN_LETTER_LINES.map((body, i) => ({
  id: `hidden-letter-${String(i + 1).padStart(3, '0')}`,
  category: 'hidden-letter',
  title: `Moment ${i + 1}`,
  location: {
    scene: 'main-hall',
    description: 'Not placed anywhere — this one only ever lives in the notebook.',
  },
  animation: { type: 'unfold', duration: 500, reversible: true },
  audio: { sfx: 'paper-unfold' },
  unlockCondition: { type: 'free' },
  notebookSection: 11,
  notebookOrder: i + 1,
  date: `Moment ${i + 1} of 100`,
  body,
  signature: '— R',
  inkVariation: INK_VARIATIONS[i % 3] ?? 'medium',
  paperRotation: ((i % 7) - 3) * 0.6,
}))
