// ─────────────────────────────────────────────────────────────────────────────
// Hidden Letters
// Never placed in a scene, never clicked to find — these live only in the
// notebook's "Hidden" section. Five unlock quietly each time one of the 20
// real collectibles is found, so all 100 are already there by the time
// everything else has been. The final letter already says it:
// "There were never one hundred reasons. There were only one hundred moments."
// This is that hundred, made real.
// ─────────────────────────────────────────────────────────────────────────────

import type { HiddenLetterMemory } from '@/types/memory'

const HIDDEN_LETTER_LINES: string[] = [
  `Some people fall in love loudly. I think I did it quietly, one ordinary Tuesday at a time.`,
  `You have the strangest way of making waiting rooms and red lights feel like good company.`,
  `I still think about that joke you made a few weeks back. It wasn't even that funny. I laughed anyway.`,
  `There's a particular kind of quiet that only happens when you're nearby, and I don't know how to explain it to anyone else.`,
  `You text like you're in a hurry, and somehow it's still my favorite thing to read.`,
  `If comfort had a shape, I think it would look a lot like you, half-asleep, mid-sentence.`,
  `I keep a mental list of things you've said that I never told you I remembered.`,
  `Some days you're the whole plan. Other days you're just the best part of it.`,
  `You've ruined ordinary Tuesdays for me. Now I expect them to be good, because of you.`,
  `I don't think you know how loud my heart gets over the smallest things you do.`,
  `You make terrible decisions sound reasonable when you explain them with that face.`,
  `I've started measuring good days by how much of them had you in them.`,
  `There's a version of me that only exists around you, and honestly, I like her better.`,
  `You interrupt my thoughts constantly. I've stopped minding.`,
  `Half of my favorite memories don't have a plot. They're just you, being around.`,
  `I don't need a reason to think about you. It just happens, like breathing, or bad weather.`,
  `You say "I'm fine" in at least four different tones, and I've learned all of them.`,
  `If I had to explain you to a stranger, I'd probably just end up smiling instead of talking.`,
  `You've never once made me feel like I was asking for too much.`,
  `I like that you argue with the TV like it can actually hear you.`,
  `There's a specific laugh you do when you're trying not to laugh, and it might be my favorite sound.`,
  `I think about the conversations we haven't had yet more than I'd like to admit.`,
  `You make plans two years out like it's obvious we'll still be doing this. I hope you're right.`,
  `I don't think I've ever met someone who remembers small things quite the way you do.`,
  `You've somehow become the answer to "what are you thinking about" more often than not.`,
  `I like the version of quiet we have. Not empty. Just comfortable.`,
  `You make bad days shorter, just by texting back.`,
  `I don't think you realize how often I'm smiling at nothing, and it's really just you.`,
  `There's a particular way you say my name when you're annoyed that I secretly enjoy.`,
  `I keep every voice message longer than I actually need to.`,
  `You've got opinions about things that don't matter, and I love hearing every one of them.`,
  `Somewhere along the way "maybe" turned into "definitely," and I didn't even notice it happening.`,
  `You make ordinary errands feel like an event, somehow.`,
  `I don't think there's a version of my week that doesn't revolve a little around talking to you.`,
  `You've got a habit of showing up right when I need the distraction.`,
  `I like that you still get shy sometimes, even now.`,
  `You've never once made fun of the things I care about, even the strange ones.`,
  `I think I fell for you somewhere between a bad joke and a long silence, and I'm still not sure which one did it.`,
  `You remember things I said in passing, weeks later, like it mattered. It did.`,
  `I've started saving photos of things that remind me of you, which is most things now.`,
  `You make the ordinary parts of a day feel less like waiting and more like living.`,
  `I don't think I tell you enough how much I notice the effort.`,
  `You've got a talent for making me feel steady when everything else isn't.`,
  `Some nights the highlight is just texting you back and forth about absolutely nothing.`,
  `I like watching you get excited about something small. It's contagious.`,
  `You've never made me feel like I had to perform to be liked.`,
  `I think the best conversations we've had started with one of us saying something ridiculous.`,
  `You make me want to be better at things I didn't used to care about.`,
  `I don't think I've laughed this much with anyone before you.`,
  `You've got a way of making apologies sound sincere even over text.`,
  `I keep thinking about the little things — how you hold a cup, how you pause before answering.`,
  `You make silence feel like a choice, not an absence.`,
  `I don't think you know how much of my day is just narrating things to you in my head.`,
  `You've earned a permanent spot on my "worth the effort" list, which is shorter than you'd think.`,
  `I like that you still ask questions you already know the answer to, just to hear me talk.`,
  `You've got a habit of making the mundane sound interesting when you explain it.`,
  `I think about how lucky the timing had to be, for us to even meet at all.`,
  `You make me want to plan things further out than I usually would.`,
  `I don't think there's a "getting used to you." It just keeps being good.`,
  `You've got a way of noticing when something's off before I even say anything.`,
  `I like the ridiculous nicknames we've made up. None of them make sense to anyone else.`,
  `You make rainy days feel like an excuse instead of an inconvenience.`,
  `I don't think I've ever wanted someone's opinion on something as much as I want yours.`,
  `You've got a specific way of teasing me that somehow still feels like affection.`,
  `I think the quiet moments with you are underrated. Nobody warns you how good those are.`,
  `You make me want to tell you things before I've even fully thought them through.`,
  `I don't think you realize how much better a day gets the second you're in it.`,
  `You've got a habit of making me feel important without ever making a big deal of it.`,
  `I like that even your bad moods don't scare me off. They just mean I get to help, a little.`,
  `You make forgetting my keys feel like a minor inconvenience instead of a disaster, somehow.`,
  `I don't think there's a single ordinary thing about you, even the ordinary things.`,
  `You've got a talent for turning "I'm bored" into an actual plan within ten minutes.`,
  `I think I like arguing with you more than agreeing with most other people.`,
  `You make me want to hold onto small moments longer than I normally would.`,
  `I don't think I say "you're my favorite" enough, so: you're my favorite.`,
  `You've got a way of making waiting for you feel worth it every single time.`,
  `I like that you still get nervous telling me good news, like I might not be excited. I always am.`,
  `You make the idea of "someday" feel less abstract and more like an actual plan.`,
  `I don't think anyone else gets the specific version of funny that we have.`,
  `You've got a habit of checking in at exactly the right moment, without me asking.`,
  `I think I've stopped noticing how much I miss you until you're back, and then it's obvious.`,
  `You make me want to write things down, just so I don't forget how a day with you felt.`,
  `I don't think there's a single conversation with you I'd take back.`,
  `You've got a way of making "us" sound like an obvious, settled fact.`,
  `I like that you still surprise me, even after all this time.`,
  `You make the idea of getting older feel less scary, knowing you'll be there for it.`,
  `I don't think I've ever had someone in my corner quite like you.`,
  `You've got a talent for turning my worst days into something manageable, just by listening.`,
  `I think about how different things would look if we'd never crossed paths, and I don't love the picture.`,
  `You make me want to be honest, even about the small, unnecessary things.`,
  `I don't think there's a limit to how many inside jokes two people can have. We're testing it.`,
  `You've got a way of making a plain Tuesday feel like it mattered.`,
  `I like that you still hold my attention completely, no matter how many times we've talked.`,
  `You make me feel like the version of myself I actually like being.`,
  `I don't think I've properly thanked you for just... staying.`,
  `You've got a habit of making hard conversations feel safer than they should.`,
  `I think the best part of my routine, honestly, is just talking to you at the end of it.`,
  `You make ordinary plans feel like something to look forward to for days.`,
  `I don't think I know how to explain what you mean to me without sounding like every other cliché — so I'll just say it plainly: you matter, more than I probably show.`,
  `However this all turns out, I wanted you to have these — a hundred small, honest things, instead of one big one I might never get exactly right. Somewhere in here, clumsily, is everything I meant to say.`,
]

const INK_VARIATIONS = ['light', 'medium', 'heavy'] as const

export const HIDDEN_LETTERS: HiddenLetterMemory[] = HIDDEN_LETTER_LINES.map((body, i) => ({
  id: `hidden-letter-${String(i + 1).padStart(3, '0')}`,
  category: 'hidden-letter',
  title: `Moment ${i + 1}`,
  location: {
    scene: 'main-hall',
    description: 'Not placed anywhere — this one only ever lives in the notebook.',
  },
  animation: { type: 'unfold', duration: 500, reversible: true },
  audio: { sfx: 'paper-unfold' },
  unlockCondition: { type: 'free' },
  notebookSection: 11,
  notebookOrder: i + 1,
  date: `Moment ${i + 1} of 100`,
  body,
  signature: '— R',
  inkVariation: INK_VARIATIONS[i % 3] ?? 'medium',
  paperRotation: ((i % 7) - 3) * 0.6,
}))
