// ─────────────────────────────────────────────────────────────────────────────
// Atmosphere Map
// Defines the complete atmospheric configuration for each EmotionState.
// This is the single source of truth for what each emotion FEELS like
// across weather, lighting, audio, and particles.
// ─────────────────────────────────────────────────────────────────────────────

import type { AtmosphereConfig, EmotionState } from '@/types/emotion'

export const ATMOSPHERE_MAP: Record<EmotionState, AtmosphereConfig> = {
  LONELY: {
    rainIntensity: 0.85,
    fogDensity: 0.6,
    windStrength: 0.3,
    hasThunder: false,
    lightWarmth: 0.1,
    lightBrightness: 0.25,
    bloomIntensity: 0.1,
    hasSunrays: false,
    ambientColor: 'rgba(10,11,20,1)',
    lightSourceColor: 'rgba(180,120,50,0.35)',
    worldFilter: 'brightness(0.65) saturate(0.5)',
    musicTrack: null,
    ambientLayers: ['rain-exterior', 'wind-platform'],
    musicVolumeMultiplier: 1.0,
    dustDensity: 0.2,
    steamDensity: 0.1,
    fireflyDensity: 0.0,
    petalDensity: 0.0,
    announcementFrequency: 0,
    announcementPool: 'none',
  },

  CURIOUS: {
    rainIntensity: 0.75,
    fogDensity: 0.45,
    windStrength: 0.25,
    hasThunder: false,
    lightWarmth: 0.25,
    lightBrightness: 0.4,
    bloomIntensity: 0.15,
    hasSunrays: false,
    ambientColor: 'rgba(13,15,22,1)',
    lightSourceColor: 'rgba(200,140,60,0.5)',
    worldFilter: 'brightness(0.75) saturate(0.65)',
    musicTrack: 'piano-entrance',
    ambientLayers: ['rain-exterior', 'rain-interior', 'station-atmosphere'],
    musicVolumeMultiplier: 0.8,
    dustDensity: 0.35,
    steamDensity: 0.3,
    fireflyDensity: 0.0,
    petalDensity: 0.0,
    announcementFrequency: 90,
    announcementPool: 'arrival',
  },

  COMFORTABLE: {
    rainIntensity: 0.55,
    fogDensity: 0.3,
    windStrength: 0.2,
    hasThunder: false,
    lightWarmth: 0.55,
    lightBrightness: 0.65,
    bloomIntensity: 0.25,
    hasSunrays: false,
    ambientColor: 'rgba(18,16,12,1)',
    lightSourceColor: 'rgba(212,132,58,0.75)',
    worldFilter: 'brightness(0.88) saturate(0.82)',
    musicTrack: 'jazz-cafe',
    ambientLayers: ['rain-interior', 'cafe-background', 'vinyl-crackle'],
    musicVolumeMultiplier: 0.9,
    dustDensity: 0.5,
    steamDensity: 0.6,
    fireflyDensity: 0.0,
    petalDensity: 0.0,
    announcementFrequency: 120,
    announcementPool: 'exploration',
  },

  NOSTALGIC: {
    rainIntensity: 0.45,
    fogDensity: 0.35,
    windStrength: 0.2,
    hasThunder: false,
    lightWarmth: 0.45,
    lightBrightness: 0.6,
    bloomIntensity: 0.2,
    hasSunrays: false,
    ambientColor: 'rgba(16,14,10,1)',
    lightSourceColor: 'rgba(184,146,42,0.7)',
    worldFilter: 'brightness(0.85) saturate(0.75) sepia(0.12)',
    musicTrack: 'ambient-tunnel',
    ambientLayers: ['rain-interior', 'station-atmosphere'],
    musicVolumeMultiplier: 0.85,
    dustDensity: 0.6,
    steamDensity: 0.4,
    fireflyDensity: 0.0,
    petalDensity: 0.0,
    announcementFrequency: 150,
    announcementPool: 'memories',
  },

  HOPEFUL: {
    rainIntensity: 0.2,
    fogDensity: 0.15,
    windStrength: 0.35,
    hasThunder: false,
    lightWarmth: 0.75,
    lightBrightness: 0.82,
    bloomIntensity: 0.4,
    hasSunrays: false,
    ambientColor: 'rgba(20,17,12,1)',
    lightSourceColor: 'rgba(212,160,80,0.9)',
    worldFilter: 'brightness(0.97) saturate(0.92)',
    musicTrack: 'piano-train',
    ambientLayers: ['train-moving', 'rain-window'],
    musicVolumeMultiplier: 1.0,
    dustDensity: 0.4,
    steamDensity: 0.7,
    fireflyDensity: 0.0,
    petalDensity: 0.0,
    announcementFrequency: 200,
    announcementPool: 'boarding',
  },

  LOVED: {
    rainIntensity: 0.0,
    fogDensity: 0.08,
    windStrength: 0.45,
    hasThunder: false,
    lightWarmth: 1.0,
    lightBrightness: 1.0,
    bloomIntensity: 0.6,
    hasSunrays: true,
    ambientColor: 'rgba(232,200,140,0.12)',
    lightSourceColor: 'rgba(232,164,90,1)',
    worldFilter: 'brightness(1.05) saturate(1.0)',
    musicTrack: 'piano-sunrise',
    ambientLayers: ['birds-morning', 'field-ambient'],
    musicVolumeMultiplier: 0.7,
    dustDensity: 0.2,
    steamDensity: 0.0,
    fireflyDensity: 0.15,
    petalDensity: 0.0,
    announcementFrequency: 0,
    announcementPool: 'none',
  },

  BEGINNING: {
    rainIntensity: 0.0,
    fogDensity: 0.04,
    windStrength: 0.6,
    hasThunder: false,
    lightWarmth: 1.0,
    lightBrightness: 1.1,
    bloomIntensity: 0.8,
    hasSunrays: true,
    ambientColor: 'rgba(245,240,232,0.2)',
    lightSourceColor: 'rgba(255,220,150,1)',
    worldFilter: 'brightness(1.1) saturate(1.1)',
    musicTrack: 'ending-uplifting',
    ambientLayers: ['birds-morning', 'field-ambient'],
    musicVolumeMultiplier: 0.9,
    dustDensity: 0.1,
    steamDensity: 0.0,
    fireflyDensity: 0.0,
    petalDensity: 0.3,
    announcementFrequency: 0,
    announcementPool: 'none',
  },
}
